version: '3'
services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
        - "5432:5432"
    restart: always

  pgadmin:
   image: dpage/pgadmin4:4.18
   container_name: pg_admin
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@admin.com
     PGADMIN_DEFAULT_PASSWORD: password
     PGADMIN_LISTEN_PORT: 80
   ports:
     - "80:80"
   volumes:
     - pgadmin-volume:/var/lib/pgadmin_postgres


volumes:
  postgres-db-volume:
  pgadmin-volume: